apiVersion: v1
kind: Pod
metadata:
  name: secret-printer
spec:
  containers:
    - name: secret-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "echo username: $(cat /etc/secret-volume/username), passowrd: $(cat /etc/secret-volume/password)" ]
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /etc/secret-volume
            readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
  restartPolicy: Never
